module.exports = [
	{
		id: 1,
		goal: "Go to store",
		date_type: "weekly",
		category: "Personal",
		added_date: "22-Jan-24",
		target_finish: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
	{
		id: 2,
		goal: "Go to store",
		date_type: "weekly",
		category: "Personal",
		added_date: "22-Jan-24",
		target_finish: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "saud123",
		status: "In Progress",
	},
	{
		id: 3,
		goal: "Go to store one more time",
		date_type: "weekly",
		category: "Personal",
		added_date: "22-Jan-24",
		target_finish: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
	{
		id: 4,
		goal: "Go to store",
		date_type: "weekly",
		category: "Personal",
		added_date: "22-Jan-24",
		target_finish: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "jane123",
		status: "In Progress",
	},
	{
		id: 5,
		goal: "Go to store again",
		date_type: "weekly",
		category: "Personal",
		added_date: "22-Jan-24",
		target_finish: "23-Jan-24",
		updated_date: "23-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
];
