module.exports = [
	{
		id: 1,
		task: "Go to store",
		category: "Personal",
		finish_date: "22-Jan-24",
		hours: "5",
		added_date: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
	{
		id: 2,
		task: "Run all day today",
		category: "Personal",
		finish_date: "22-Jan-24",
		hours: "5",
		added_date: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
	{
		id: 3,
		task: "do some work",
		category: "Work",
		finish_date: "28-Jan-24",
		hours: "3",
		added_date: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "In Progress",
	},
	{
		id: 4,
		task: "Go to store",
		category: "Personal",
		finish_date: "22-Jan-24",
		hours: "5",
		added_date: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "john123",
		status: "Not Started",
	},
	{
		id: 5,
		task: "Go to store",
		category: "Personal",
		finish_date: "22-Jan-24",
		hours: "5",
		added_date: "22-Jan-24",
		updated_date: "22-Jan-24",
		user_id: "sam123",
		status: "In Progress",
	},
];
