module.exports = [
	{
		id: 1,
		username: "saud123",
		password: "helloworld",
		email: "kingman@gmail.com",
		first_name: "Saud",
		last_name: "Ahmed",
		added_date: "22-Jan-24",
		updated_date: "23-Jan-24",
	},
	{
		id: 2,
		username: "john123",
		password: "helloworld",
		email: "kingdoe@gmail.com",
		first_name: "John",
		last_name: "Doe",
		added_date: "23-Jan-24",
		updated_date: "24-Jan-24",
	},
	{
		id: 3,
		username: "jane123",
		password: "helloworld",
		email: "queendoe@gmail.com",
		first_name: "Jane",
		last_name: "Doe",
		added_date: "24-Jan-24",
		updated_date: "25-Jan-24",
	},
];
